name: todo_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  auto_route: ^8.2.0
  firebase_auth: ^5.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  
  flutter_hooks: ^0.20.5
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  luthor: ^0.3.2+1
  luthor_annotation: ^0.3.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  flutter_lints: ^3.0.0
  build_runner: ^2.4.11
  auto_route_generator: ^8.0.0
  json_serializable: ^6.8.0
  luthor_generator: ^0.4.1

flutter:
  uses-material-design: true
