// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbnmXy78F0dXVj9QtEy_lgo4PAtsZJ41M',
    appId: '1:110252614893:web:81f40e401be3de287b98e4',
    messagingSenderId: '110252614893',
    projectId: 'todoapp-a899a',
    authDomain: 'todoapp-a899a.firebaseapp.com',
    storageBucket: 'todoapp-a899a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKN9VqTqGjYL_owndciPBqOddWwJpo8ss',
    appId: '1:110252614893:android:082fe07da3084a1c7b98e4',
    messagingSenderId: '110252614893',
    projectId: 'todoapp-a899a',
    storageBucket: 'todoapp-a899a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvg_sgVAigMUg1gu9U7QplmgO-clPXmq4',
    appId: '1:110252614893:ios:b155f0b00538b8047b98e4',
    messagingSenderId: '110252614893',
    projectId: 'todoapp-a899a',
    storageBucket: 'todoapp-a899a.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );
}
